import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"></meta>
        <link rel="icon" href="/faviocn.ico" />
      </Head>

      <h1 className="text-3xl font-bold"> Next Sale App </h1>
    </div>
  );
}
